Thumbnail Service and Docker Multi Arch
Segelzwerg/FamilyFoto pull request #57
Opened 2020-11-24 22:44 UTC by Segelzwerg

2020-11-25 09:20 UTC, iTitus submitted a review, later dismissed

2020-11-25 10:07 UTC, Segelzwerg commented
maybe we should wait for #60 as this application is not very useful without storage outside the container.

2020-11-25 10:44 UTC, iTitus requested changes

2020-11-25 10:44 UTC, iTitus commented on .github/workflows/docker-image.yml
> +    - name: Update Packages
```suggestion
    - name: Update Package Index
```

2020-11-25 10:44 UTC, iTitus commented on .github/workflows/docker-publish.yml
> +      - uses: actions/checkout@v2
Should also update the package index here, just to be safe

2020-11-26 18:22 UTC, iTitus approved these changes

2020-11-26 18:29 UTC, merged